### PR TITLE
Set tombstone and partition healing tests to mandatory

### PR DESCRIPTION
**Pull request by CorgiMan**

### CODE REVIEW

**Comment by thanodnl** [comment]
LGTM

we might want to remove the feature flags at some point from the test runner in `ringpop-node` and `ringpop-go`

**Comment by btromanova** [comment]
LGTM

**Comment by mbrysa** [comment]
LGTM

**Comment by severb** [comment]
LGTM

**Comment by mennopruijssers** [comment]
LGTM!

**Comment by dansimau** [comment]
LGTM

**Comment by CorgiMan** [comment]
LGTM

**Comment by danielheller** [comment]
lgtm!

**Pull request merged**
