### PR TITLE
Update /admin/reap to return reaped nodes count

### PR DESCRIPTION
**Pull request by severb**
See https://github.com/uber/ringpop-node/pull/257#discussion_r62028527 for context.

### CODE REVIEW

**Comment by dansimau** [comment]
Can you elaborate more in the description? I don't understand what this is doing. It doesn't seem like it is doing what the title says.

**Comment by severb** [comment]
It modifies the /admin/reap test to expect a count instead of `ok`.

**Comment by dansimau** [comment]
Great. Would you mind adding it to the description with a bit of context?

I'm on the war path to get people to write good descriptions because it helps with releases. It only takes 20 seconds to do this and really helps everyone with reviewing or keeping an eye on the projects... 😄

**Comment by severb** [comment]
Totally agree, I added a link for more context.

**Comment by dansimau** [comment]
Doesn't this break the integration test for ringpop-go?
https://github.com/uber/ringpop-go/blob/dev/swim/handlers.go#L162

**Comment by severb** [comment]
It does if you enable testing for the reaping-faulty-nodes feature. We'll do a similar change in ringpop-go before this feature is enabled by default.

**Comment by dansimau** [comment]
Am I missing something? I thought it was already enabled by default in ringpop-go...
https://github.com/uber/ringpop-go/blob/master/test/run-integration-tests#L109

**Comment by severb** [comment]
Oh, you're right! Good catch, I'll need to update this PR.

**Comment by thanodnl** [comment]
LGTM

**Comment by dansimau** [comment]
LGTM

**Comment by severb** [comment]
Thanks!!

**Pull request merged**
